version: "3.7"
services:
  worker:
    build: .
    container_name: logging
    volumes:
      - .:/app
    networks:
      - traefik-public
    env_file:
      - .env
    restart: on-failure
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "./main.py"]
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

networks:
  traefik-public:
    external: true
