version: "3.9"
services:
  worker:
    build: .
    container_name: logging
    volumes:
      - .:/app
    networks:
      - traefik-public
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    command: ["python", "main.py"]

networks:
  traefik-public:
    external: true
