name: build-and-publish-docker-logging

on:

  workflow_dispatch:

  repository_dispatch:
    types: [build-and-publish-docker-logging]

  push:
    branches:
      - "master"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get tag latest
        id: tag_latest
        run: echo "::set-output name=tag_latest::$(echo $(echo ${{ github.ref_name }} | sed 's/[^a-z]*//g' | sed 's/^master//g'; echo latest) | tr " " ".")"
      - name: Log tags
        id: log_tags
        run: |
          echo ${{ steps.tag_latest.outputs.tag_latest }}
          echo ${{ github.ref_name }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            interlinkproject/backend-logging:${{ steps.tag_latest.outputs.tag_latest }}
            interlinkproject/backend-logging:${{ github.ref_name }}
            interlinkproject/backend-logging:${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=interlinkproject/backend-logging:buildcache
          cache-to: type=registry,ref=interlinkproject/backend-logging:buildcache,mode=max
